title: My site
author: Tokotomka
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Test job
  hmm

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
